use super::chmp::{Conditional, Expr, Group, Handle, Op, Override, Policy, Statement};

pub fn encode(policy: &Policy, modname: &str, source: &str) -> String {
    let mut out = String::new();

    out.push_str(&format!("// generated by embroider from {source}\n"));
    out.push_str("use crate::embroider::chmp::*;\n\n");
    out.push_str(&format!("pub fn {modname}() -> Policy {{\n"));
    out.push_str("    Policy {\n");

    encode_stmt_field(&mut out, "on_startup", &policy.on_startup);
    encode_stmt_field(&mut out, "on_exit", &policy.on_exit);

    encode_groups(&mut out, &policy.groups);
    encode_handles(&mut out, &policy.handles);
    encode_overrides(&mut out, &policy.overrides);

    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

fn encode_stmt_field(out: &mut String, name: &str, stmts: &[Statement]) {
    if stmts.is_empty() {
        out.push_str(&format!("        {name}: vec![],\n"));
        return;
    }
    out.push_str(&format!("        {name}: vec![\n"));
    for s in stmts {
        encode_stmt(out, "            ", s);
    }
    out.push_str("        ],\n");
}

fn encode_groups(out: &mut String, groups: &[Group]) {
    if groups.is_empty() {
        out.push_str("        groups: vec![],\n");
        return;
    }
    out.push_str("        groups: vec![\n");
    for g in groups {
        out.push_str("            Group {\n");
        out.push_str(&format!("                name: {}.into(),\n", esc(&g.name)));
        out.push_str("                syscalls: vec![\n");
        for s in &g.syscalls {
            out.push_str(&format!("                    {}.into(),\n", esc(s)));
        }
        out.push_str("                ],\n");
        out.push_str("            },\n");
    }
    out.push_str("        ],\n");
}

fn encode_handles(out: &mut String, handles: &[Handle]) {
    if handles.is_empty() {
        out.push_str("        handles: vec![],\n");
        return;
    }
    out.push_str("        handles: vec![\n");
    for h in handles {
        out.push_str("            Handle {\n");
        out.push_str(&format!("                group: {}.into(),\n", esc(&h.group)));
        out.push_str("                body: vec![\n");
        for s in &h.body {
            encode_stmt(out, "                    ", s);
        }
        out.push_str("                ],\n");
        out.push_str("            },\n");
    }
    out.push_str("        ],\n");
}

fn encode_overrides(out: &mut String, overrides: &[Override]) {
    if overrides.is_empty() {
        out.push_str("        overrides: vec![],\n");
        return;
    }
    out.push_str("        overrides: vec![\n");
    for o in overrides {
        out.push_str("            Override {\n");
        out.push_str(&format!("                name: {}.into(),\n", esc(&o.name)));
        out.push_str("                body: vec![\n");
        for s in &o.body {
            encode_stmt(out, "                    ", s);
        }
        out.push_str("                ],\n");
        out.push_str("            },\n");
    }
    out.push_str("        ],\n");
}

fn encode_stmt(out: &mut String, indent: &str, stmt: &Statement) {
    match stmt {
        Statement::Allow => out.push_str(&format!("{indent}Statement::Allow,\n")),
        Statement::Deny => out.push_str(&format!("{indent}Statement::Deny,\n")),
        Statement::EchoArgs => out.push_str(&format!("{indent}Statement::EchoArgs,\n")),
        Statement::Echo(msg) => {
            out.push_str(&format!("{indent}Statement::Echo({}.into()),\n", esc(msg)));
        }
        Statement::Modify(arg, value) => {
            out.push_str(&format!(
                "{indent}Statement::Modify({}.into(), {}),\n",
                esc(arg),
                encode_expr(value)
            ));
        }
        Statement::Bind(source, destination) => {
            out.push_str(&format!(
                "{indent}Statement::Bind({}.into(), {}.into()),\n",
                esc(source),
                esc(destination)
            ));
        }
        Statement::Assign(name, value) => {
            out.push_str(&format!(
                "{indent}Statement::Assign({}.into(), {}),\n",
                esc(name),
                encode_expr(value)
            ));
        }
        Statement::Conditional(cond) => encode_conditional(out, indent, cond),
    }
}

fn encode_conditional(out: &mut String, indent: &str, cond: &Conditional) {
    let inner = format!("{indent}    ");
    let deep = format!("{inner}    ");

    out.push_str(&format!("{indent}Statement::Conditional(Conditional {{\n"));
    out.push_str(&format!("{inner}expr: {},\n", encode_expr(&cond.expr)));

    if cond.then.is_empty() {
        out.push_str(&format!("{inner}then: vec![],\n"));
    } else {
        out.push_str(&format!("{inner}then: vec![\n"));
        for s in &cond.then {
            encode_stmt(out, &deep, s);
        }
        out.push_str(&format!("{inner}],\n"));
    }

    match &cond.otherwise {
        Some(stmts) => {
            if stmts.is_empty() {
                out.push_str(&format!("{inner}otherwise: Some(vec![]),\n"));
            } else {
                out.push_str(&format!("{inner}otherwise: Some(vec![\n"));
                for s in stmts {
                    encode_stmt(out, &deep, s);
                }
                out.push_str(&format!("{inner}]),\n"));
            }
        }
        None => out.push_str(&format!("{inner}otherwise: None,\n")),
    }

    out.push_str(&format!("{indent}}}),\n"));
}

fn encode_expr(expr: &Expr) -> String {
    match expr {
        Expr::Ident(name) => format!("Expr::Ident({}.into())", esc(name)),
        Expr::String(s) => format!("Expr::String({}.into())", esc(s)),
        Expr::Call(name, args) => {
            let args: Vec<String> = args.iter().map(encode_expr).collect();
            format!("Expr::Call({}.into(), vec![{}])", esc(name), args.join(", "))
        }
        Expr::BinOp(left, op, right) => {
            let op = match op {
                Op::BitOr => "Op::BitOr",
                Op::BitAnd => "Op::BitAnd",
                Op::Or => "Op::Or",
                Op::And => "Op::And",
            };
            format!(
                "Expr::BinOp(Box::new({}), {op}, Box::new({}))",
                encode_expr(left),
                encode_expr(right)
            )
        }
    }
}

fn esc(s: &str) -> String {
    format!("{s:?}")
}
