// generated by embroider from embroider/hello.chmp
use crate::embroider::chmp::*;

pub fn hello() -> Policy {
    Policy {
        on_startup: vec![
            Statement::Echo("starting chimera".into()),
            Statement::Bind("/proc".into(), "/chimera/rootfs/proc".into()),
            Statement::Bind("/sys".into(), "/chimera/rootfs/sys".into()),
            Statement::Bind("/dev".into(), "/chimera/rootfs/dev".into()),
        ],
        on_exit: vec![
            Statement::Echo("stopping chimera".into()),
        ],
        groups: vec![
            Group {
                name: "filesystem".into(),
                syscalls: vec![
                    "openat".into(),
                    "openat2".into(),
                    "read".into(),
                    "write".into(),
                    "close".into(),
                    "stat".into(),
                    "statx".into(),
                    "newfstatat".into(),
                ],
            },
            Group {
                name: "process".into(),
                syscalls: vec![
                    "clone".into(),
                    "fork".into(),
                    "execve".into(),
                    "exit".into(),
                    "wait4".into(),
                ],
            },
            Group {
                name: "networking".into(),
                syscalls: vec![
                    "socket".into(),
                    "connect".into(),
                    "bind".into(),
                    "listen".into(),
                ],
            },
        ],
        handles: vec![
            Handle {
                group: "filesystem".into(),
                body: vec![
                    Statement::Assign("path".into(), Expr::Call("get_arg".into(), vec![Expr::Ident("path".into())])),
                    Statement::Conditional(Conditional {
                        expr: Expr::Call("regex".into(), vec![Expr::Ident("path".into()), Expr::String("^/chimera/rootfs".into())]),
                        then: vec![
                            Statement::Allow,
                        ],
                        otherwise: Some(vec![
                            Statement::Modify("path".into(), Expr::Call("map_path".into(), vec![Expr::Ident("root".into()), Expr::Ident("path".into())])),
                            Statement::Allow,
                        ]),
                    }),
                ],
            },
            Handle {
                group: "networking".into(),
                body: vec![
                    Statement::Echo("network syscall".into()),
                    Statement::Allow,
                ],
            },
        ],
        overrides: vec![
            Override {
                name: "openat".into(),
                body: vec![
                    Statement::Assign("path".into(), Expr::Call("get_arg".into(), vec![Expr::Ident("path".into())])),
                    Statement::Conditional(Conditional {
                        expr: Expr::Call("regex".into(), vec![Expr::Ident("path".into()), Expr::String("/etc/passwd".into())]),
                        then: vec![
                            Statement::Deny,
                        ],
                        otherwise: None,
                    }),
                    Statement::Modify("path".into(), Expr::Call("map_path".into(), vec![Expr::Ident("root".into()), Expr::Ident("path".into())])),
                    Statement::Allow,
                ],
            },
            Override {
                name: "uname".into(),
                body: vec![
                    Statement::Echo("fake uname".into()),
                    Statement::Modify("buffer".into(), Expr::String("Chimera Linux".into())),
                    Statement::Allow,
                ],
            },
        ],
    }
}
